### PR TITLE
fix(bug): make 'scope' skippable if found in skipQuestions

### LINKED ISSUE #672: [BUG] can't skip questions
when i add for example "scope" to the skipQuestions the question remains

### PR DESCRIPTION
**Pull request by TibebeJS**
Closes #672

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -388,7 +388,7 @@ class ConventionalCommitMessage {
   private static shouldSkip(
     czConfig: CzConfig | undefined,
     messageType: string
-  ): czConfig is CzConfig {
+  ): boolean {
```
Comment (KnisterPeter) [inline src/extension.ts:391]: Why did you change this? The typescript 'x is y' return implies a boolean result as well as narrowing the type.
Effectivity you are weakening the compiler here.

**Review by KnisterPeter — CHANGES_REQUESTED** [review]

File: src/extension.ts (hunk 1 above)
Comment (TibebeJS) [reply src/extension.ts:391]: Understood. sorry for that

Comment (KnisterPeter) [reply src/extension.ts:391]: Nothing to be sorry for. 😃

File: src/extension.ts [hunk 2]
```diff
@@ -433,7 +433,7 @@ class ConventionalCommitMessage {
   private static allowBreakingChanges(
     czConfig: CzConfig | undefined,
     selectedType: string | undefined
-  ): boolean {
+  ): czConfig is CzConfig {
```
Comment (KnisterPeter) [inline src/extension.ts:436]: Oh, I think you reverted in the wrong line, right?

**Review by KnisterPeter — CHANGES_REQUESTED** [review]

File: src/extension.ts (hunk 2 above)
Comment (TibebeJS) [reply src/extension.ts:436]: how clumsy of me! OMG

File: src/extension.ts (hunk 1 above)
Comment (TibebeJS) [reply src/extension.ts:391]: changing that is causing some linting issues:
```
 error TS2339: Property 'scopes' does not exist on type 'never'.

480         if (this.czConfig.scopes && this.czConfig.scopes[0] !== undefined) {
```

Comment (TibebeJS) [reply src/extension.ts:391]: > changing that is causing some linting issues:
> 
> ```
>  error TS2339: Property 'scopes' does not exist on type 'never'.
> 
> 480         if (this.czConfig.scopes && this.czConfig.scopes[0] !== undefined) {
> ```


this doesn't happen when the return type is `boolean`

Comment (KnisterPeter) [reply src/extension.ts:391]: The error means the type is not possible and would result in never executed code.
I guess the typing is incorrect. I take a look later on.

Comment (TibebeJS) [reply src/extension.ts:391]: okay thanks for your time! I am a typescript noob :)

File: src/extension.ts (hunk 2 above)
Comment (TibebeJS) [reply src/extension.ts]: I have reverted my change in there

File: src/extension.ts (hunk 1 above)
Comment (KnisterPeter) [reply src/extension.ts:391]: After having a look I have to say sorry :smiley: 
Your first change wasn't that bad. The code is quiet old and TypeScript evolved. I thing it might need a complete overhaul to be more understandable.
Please change it it `boolean` again. I'm happy to merge it.

**Review by KnisterPeter — CHANGES_REQUESTED** [review]

File: src/extension.ts (hunk 1 above)
Comment (TibebeJS) [reply src/extension.ts:391]: sure :) but I think the return type is `boolean` at the current state

Comment (TibebeJS) [reply src/extension.ts:391]: Hello @KnisterPeter, any news?

**Review by KnisterPeter — APPROVED** [review]
@TibebeJS Sorry, thanks for your contribution :tada:
